filme/urls.py
# Criar sempre 3 coisas: URL, View e Template
from django.urls import path, reverse_lazy
from .views import Homepage, Homefilmes, Detalhesfilme, Pesquisafilme, Editarperfil, Criarconta
from django.contrib.auth import views as auth_view

app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('editarperfil/<int:pk>', Editarperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),
]

# <int:pk>: ele indentifica que esse parâmetro (valor depois da /) tem que ser a primary key (pk) de um item do modelo
# Nesse caso,é basicamente para dizer que,para acessar um filme específico,basta colocar o id do filme após o 'filmes/'

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.

# LISTA_CATEGORIAS = (
#     ("Armazenar no Banco de Dados", "Aparecer para o Usuário"),
# )

LISTA_CATEGORIAS = (
    ("ANALISES", "Análises"),
    ("PROGRAMACAO", "Programação"),
    ("APRESENTAÇÃO", "Apresentação"),
    ("OUTROS", "Outros")
)

# Criar o Filme
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    qtd_views = models.IntegerField(default=0)
    data_criacao =models.DateTimeField(default=timezone.now)

    # Exibir o Nome do Filme/Curso na Página de Admin (sem isso, ele exibe assim: Filme object (1))
    def __str__(self):
        return self.titulo

# Criar os Episódios
class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE) # Cria a relação 1 para
    # muitos com o Filme
    # "Filme": Nome da Tabela que ele vai se relacionar
    # related_name="episodios": serve para descobrir os episódios de determinado filme, vai ser um lista de episódios
    # on_delete=models.CASCADE: faz com que os episódios de um filme que foi excluído, sejam deletados automaticamente
    # Se eu quisesse criar uma relação de muito para muitos, eu deveria usar ManyToManyField ao invés de ForeignKey
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo

# Criar o Usuário
class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms

class FormHomepage(forms.Form):
    email = forms.EmailField(label=False) # label=False: Serve para não exibir o Texto do Formulário

class CriarContaForm(UserCreationForm):
    email = forms.EmailField() # Por padrão, ao deixar vazio os argumentos, o campo se torna obrigatório

    # Class Meta (serve para dizer qual modelo ele deve usar com referência)
    class Meta:
        model = Usuario
        # Campos que serão Exibidos no Formulário
        fields = ('username', 'email', 'password1', 'password2') # 'password1': Campo Senha
        # 'password2': Campo Confirmação de Senha

filme/views.py
from django.shortcuts import render, redirect, reverse
from.models import Filme, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin # Tem que ser o 1º Argumento da Classe

# Create your views here.
class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('filme:homefilmes')
        else:
            return super().get(request, *args, **kwargs) # Redireciona o Usuário para a Homepage

    # Redirecionar a Pessoa de maneira Inteligente
    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            # Levar para a Página de Login, caso o usuário tenha uma conta no site
            return reverse('filme:login')
        else:
            # Levar para a Página de Criar Conta, caso o usuário não tenha uma conta no site
            return reverse('filme:criarconta')

class Homefilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    model = Filme

class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilme.html"
    model = Filme

    # Função para contabilizar a Visualização no Filme
    def get(self, request, *args, **kwargs): # Essa Função espera um Redirecionamento (uma Página como resposta)
        filme = self.get_object()
        filme.qtd_views += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super(Detalhesfilme, self).get(request, *args, **kwargs) # Redireciona o Usuário para a URL final

    # View Filmes Relacionados que estará disponível apenas nessa página
    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self).get_context_data(**kwargs) # Para manter a função principal
        # (não sobrescrevê-la, apenas adicionar as próximas linhas de código na função)
        # Filtrar a Tabela de Filmes pegando apenas os itens com a Categoria da Página
        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)[0:8]
        context['filmes_relacionados'] = filmes_relacionados
        return context

class Pesquisafilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = self.model.objects.filter(titulo__icontains=termo_pesquisa)
            return object_list
        else:
            return None

class Editarperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('filme:homefilmes')

class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    # Função que verifica se o Formulário é Válido (salvar alterações no Banco de Dados, criar uma conta)
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    # Função para o Formulário bem sucedido (validação der certo)
    def get_success_url(self): # Essa Função espera uma URL (um Link como resposta)
        return reverse('filme:login')

filme/templates/detalhesfilme.html
{% extends 'base.html' %}

{% block titulo %}
HomeFilmes Hashflix
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <!-- Seção de Destaque para o Filme -->
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{ object.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                <!-- |slice:":50": Serve para cortar o texto em 50 caracteres-->
                {{ object.descricao|slice:":50" }}...
            </p>
            <!-- Botão de Play (Vai levar para o 1º Episódio) -->
            <div class="flex my-4">
                <a href="{{ object.episodios.first.video }}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <!-- Seção de Características do Filme -->
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }}
                    <br>
                    <!-- Exibir a quantidade de visualizações -->
                    Visualizações: {{ object.qtd_views }}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios

                </h2>
                {% for episodio in object.episodios.all %}
                    <h3 class='text-lg'>
                        <!-- forloop.counter: no Django serve como um enumerate dentro do for -->
                        <a href="{{ episodio.video }}"><p>Episódio {{ forloop.counter }}: {{ episodio.titulo }}</p></a>
                    </h3>
                {% endfor %}
            </div>

        </div>
    </section>
    <!-- Seção de Filmes Relacionados -->
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme in filmes_relacionados %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.id %}">
                            <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil Hashflix
{% endblock %}

{% block content %}
<!-- Formulário Editar PErfil -->
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl">{{ user.username }}</h2>
        <br>
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
        </form>
        <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
    </div>
</header>
<!-- Rodapé da Página -->
<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Hashtag</li>
    </ul>
</footer>
{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomeFilmes Hashflix
{% endblock %}

{% block head %}
<!-- Parte em CSS que permite com que o Carrossel de Filmes funcione adequadamente -->
<style>
    $itemGrow: 1.2;
$duration: 250ms;

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
}

h1 {
  font-family: Arial;
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;

    .item {
      padding: 0 2px;
      transition: $duration all;

      &:hover {
        margin: 0 40px;
        transform: scale(1.2);
      }

    }

    a {
      position: absolute;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;

      &:nth-of-type(1) {
        top:0; bottom:0; left:0;
        background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }
      &:nth-of-type(2) {
        top:0; bottom:0; right: 0;
        background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
      }

    }

  }
}

// Remove the arrow for Mobile
@media only screen and (max-width: 600px) {
  a.arrow__btn {
    display:none;
  }
}
</style>
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ filme_destaque.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">{{ filme_destaque.titulo }}</h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">{{ filme_destaque.descricao|slice:":50" }}...</p>
            <div class="flex my-4">
                <a href="{% url 'filme:detalhesfilme' filme_destaque.id %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium " >
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <!-- Seção Lançamentos -->
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Lançamentos
            </h2>
            <div class="wrapper">
                <!--id="a": Permite que, ao clicar em um link, seja levado para outra página, ao invés de outra seção -->
                <section id="section1lancamento" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2lancamento" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in lista_filmes_recentes %}
                        {% if forloop.counter < 5 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'filme:detalhesfilme' filme.id %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <a href="#section2lancamento" class="arrow__btn text-6xl">›</a>
                </section>
                {% if lista_filmes_recentes|length > 4 %} <!-- Exibir a 2ª seção caso tenha mais de 4 filmes recentes -->
                    <section id="section2lancamento" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1lancamento" class="arrow__btn text-6xl">‹</a>
                        {% for filme in lista_filmes_recentes %}
                            {% if forloop.counter > 4 %}
                                <div class="item h-64 w-1/4 m-4">
                                    <a href="{% url 'filme:detalhesfilme' filme.id %}">
                                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <a href="#section1lancamento" class="arrow__btn text-6xl">›</a>
                    </section>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Seção Em Alta -->
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Em Alta
            </h2>
            <div class="wrapper">
                <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in lista_filmes_em_alta %}
                        {% if forloop.counter < 5 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'filme:detalhesfilme' filme.id %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
                </section>
                {% if lista_filmes_em_alta|length > 4 %}
                    <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                        {% for filme in lista_filmes_em_alta %}
                            {% if forloop.counter > 4 %}
                                <div class="item h-64 w-1/4 m-4">
                                    <a href="{% url 'filme:detalhesfilme' filme.id %}">
                                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                    </section>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Seção Assistir Novamente -->
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Assistir Novamente
            </h2>
            <div class="wrapper">
                <section id="section1assistirnovamente" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2assistirnovamente" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in request.user.filmes_vistos.all %}
                        {% if forloop.counter < 5 %}
                            <div class="item h-64 w-1/4 m-4">
                                <a href="{% url 'filme:detalhesfilme' filme.id %}">
                                    <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <a href="#section2assistirnovamente" class="arrow__btn text-6xl">›</a>
                </section>
                {% if request.user.filmes_vistos.all|length > 4 %}
                    <section id="section2assistirnovamente" class="flex flex-nowrap items-center justify-center">
                        <a href="#section1assistirnovamente" class="arrow__btn text-6xl">‹</a>
                        {% for filme in request.user.filmes_vistos.all %}
                            {% if forloop.counter > 4 %}
                                <div class="item h-64 w-1/4 m-4">
                                    <a href="{% url 'filme:detalhesfilme' filme.id %}">
                                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <a href="#section1assistirnovamente" class="arrow__btn text-6xl">›</a>
                    </section>
                {% endif %}
            </div>
        </div>
    </section>
</main>
{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
HomePage Hashflix
{% endblock %}

<!-- Formatar o Formulário -->
{% block head %}
<style>
    #id_email{
    width: 100%;
    color: #000000;
    padding: 5px 5px;
    }
</style>
{% endblock %}

{% block content %}
<!-- É a estrutura que vai ocupar a primeira dobra da página, a primeira coisa que a pessoa vê que ocupa a tela inteira -->
<!-- bg-blend-overlay: Colocar uma imagem sobre a outra (fundo preto e a foto com os filmes -->
<!-- style="background-image: Modifica a Imagem de Fundo -->
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Filmes e séries da Hashtag, tudo em um só lugar.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Assista onde quiser. Cancele quando quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar.
        </h4>
        <!-- Formulário de Acessar -->
        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <form method="post" class="w-6/12 justify-center">
                    {% csrf_token %}
                    <div class="flex flex-grow items-stretch">
                        {{ form }}
                    <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                        <span>
                            Acessar
                        </span>
                        <!-- Ícone ao lado de "Acessar" -->
                        <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                    </button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <!-- Texto -->
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Enjoy on your TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
        </h5>
    </div>
    <!-- Imagem -->
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center '>
        <img src="{% static 'images/mobile-0819.jpg' %}" class="w-8/12" alt="">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Download your shows to watch offline.
        </h2>
        <h5 class="md:text-xl text-lg">
            Save your favorites easily and always have something to watch.
        </h5>
    </div>

</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Create profiles for kids.
        </h2>
        <h5 class="md:text-xl text-lg">
            Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
    </div>
</section>

<!-- Rodapé da Página -->
<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">

        <li>&copy; 2023</li>
        <li> Feito com Python (Django)</li>
        <li>Vinícius Cerri</li>
    </ul>
</footer>
{% endblock %}

templates/navbar.html
<!-- Colocar Imagem da Pasta static -->
{% load static %}

<!-- w-full: faz com que a Barra de Navegação tenha a largura da Página Inteira -->
<!-- flex: essa classe é como se fosse um contêiner de itens, ela controla como os itens dentro dela vão se comportar -->
<!-- justify-between: deixa os itens de forma equidistantes entre eles-->
<!-- items-center: centraliza os itens na vertical-->
<!-- py e px (padding): é a distância entre o conteúdo de um elemento e suas bordas (margem interna) -->
<!-- fixed: diz que a Barra de Navegação vai ficar fixa no topo -->
<!-- z: serve para criar um eixo z, os valores que forem menores do que o valor que vem depois do traço ficarão atrás -->
<!-- da Barra de Navegação, enquanto os que forem maiores ficarão a frente -->
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <!-- w-6/12: Serve para dividir ao meio a Barra de Navegação-->
    <div class="w-6/12">
        <a href="/">
            <img class="w-2/12" src="{% static 'images/hashflix.png' %}">
        </a>
    </div>
    <!-- flex-nowrap: Colocar os elementos um do lado do outro -->
    <!-- justify-end: Alinhar à Direita -->
    <div class="w-6/12 flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
            <!-- mr: Margem à Direita -->
            <div class="mr-2">
                <!-- Formulário de Pesquisa -->
                <form method="get" action="{% url 'filme:pesquisafilme' %}">
                    <!-- rounded-md: Borda Redonda -->
                    <!-- placeholder: Texto Default -->
                    <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar">
                    <input type="submit" value="">
                </form>
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <div class="mr-2">
                <a href="{% url 'filme:logout' %}">
                    <!-- bg-primary_red: Mudar o Fundo do Botão para Vermelho -->
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">Sair</button>
                </a>
            </div>
        {% else %}
            <div class="mr-2">
                <a href="{% url 'filme:login' %}">
                    <!-- bg-primary_red: Mudar o Fundo do Botão para Vermelho -->
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">Login</button>
                </a>
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <div class="mr-2">
                <a href="{% url 'filme:editarperfil' user.id %}">
                    <button class="bg-red-600 text-white py-1 px-3 rounded-md">Editar Perfil</button>
                </a>
            </div>
        {% endif %}
    </div>
</nav>